### PR TITLE
Included method for deleting users & Fixed UpdateUserInformationAsync method

### PR DESCRIPTION
**Pull request by ljbotero**
- Included method for deleting users
- Fixed UpdateUserInformationAsync method as it wasn't using the correct http verb as documented in the API @ https://developers.box.com/docs/#users-update-a-users-information

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @ljbotero, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by cburnette** [comment]
Method name is misspelled:

DeleteEnterpirseUserAsync

**Comment by ljbotero** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @ljbotero has just signed the CLA. Thanks, and we look forward to your contribution.

**Pull request merged**
