### PR TITLE
Added new optional parameters to BoxSearchManager.SearchAsync()

### PR DESCRIPTION
**Pull request by JogyBlack**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @JogyBlack, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by JogyBlack** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @JogyBlack has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by davidmurdoch** [comment]
Will this be merged in anytime soon?

**Comment by cburnette** [comment]
Yes, I'm planning to fully implement advanced search including metadata next week. This will include this functionality. 

Chad

**Comment by cburnette** [comment]
just merged in a different branch that added full support for all search params

**Pull request closed without merging**
