### PR TITLE
Added asUser parameter to GetFolderItemsAsync

### PR DESCRIPTION
**Pull request by zeus82**
Needed to be able to traverse all folders for users in my organization.  I found that once I requested the root folder for a user I was able to traverse their folder structures without using the "As-User" header.  For that reason I limited my changes to GetFolderItemsAsync and some methods it calls.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @zeus82, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by cburnette** [comment]
Hi @zeus82 , thanks for the pull request.  I'll actually be adding As-User support shortly that works across all endpoints.  Once I do I'll close out this pull request as notification.  thanks!

**Comment by zeus82** [comment]
That's great!  Any idea on when it will be available?

**Comment by cburnette** [comment]
yes, I'll probably be releasing this as a new Nuget package tomorrow.

**Comment by cburnette** [comment]
hey, just release the version 2.6.0 with As-User support.  Check out the README for an example of using it.

**Comment by cburnette** [comment]
https://github.com/box/box-windows-sdk-v2/blob/master/README.md#make-api-calls-with-as-user

**Pull request closed without merging**
