### PR TITLE
Update BoxFilesManager.cs

### PR DESCRIPTION
**Pull request by ajweber**
Added methods for:
RefreshInformationAsync (use If-None-Match with eTag to only download file metadata if it has changed)
AddFileToFavoritesAsync (add file to user's favorites collection)
RemoveFileFromFavoritesAsync (remove file from user's favorites collection)

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @ajweber, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by ajweber** [comment]
Agreed to CLA.

**Comment by ajweber** [comment]
Sorry, it requires addition of an IfNoneMatch Request constant and probably "using System.Net;" for the HttpCode constants.

These are some old edits that I am trying to resolve migrating to the newest code.

**Comment by ajweber** [comment]
Going to re-package my updates into a new pull request tested with local compilation (instead of GitHub direct edits).  New Pull Request to follow shortly.  Sorry.

**Pull request closed without merging**
