### PR TITLE
#389 interface extraction extravaganza

### PR DESCRIPTION
**Pull request by Cpcrook**
Per #389 there was a request for manager interfaces.  This branch takes care of all of the Manager classes, and provides an interface for IBoxClient as well.

However, using a mocking framework like Moq, this doesn't quite get over the hurdle of being unable to effectively mock any of the models properly due to non-virtual properties, so I'll be submitting a second branch PR for this issue, in the event that you accept one and not the other.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @Cpcrook has signed the CLA. Thanks for the pull request!

**Comment by carycheng** [comment]
@Cpcrook, again we really appreciate the work you have put into this! We'll review all these pr's and update you, thank you!

**Comment by PJSimon** [comment]
Hi @Cpcrook!
Thanks so much for this contribution!  I just wanted to follow up and give you an expectation of time frame for our response.  

The team is focused on a release this week for the [box-ios-sdk](https://github.com/box/box-ios-sdk).  So, we will review your PR on Thursday of next week and will respond later that day!

Thanks again!

**Comment by Cpcrook** [comment]
I appreciate the update regarding timing @PJSimon !

**Comment by estevens-psecu** [comment]
When can we expected this PR to be merged?
We are unable to write unit tests for our code that is making use of the box sdk.

**Comment by Cpcrook** [comment]
@estevens-psecu I'll make sure I've signed the CLA (again, as the comment history indicates I already did).

Hopefully they'll get to it eventually.

**Comment by mwwoda** [comment]
Changes already included under #735.

**Pull request closed without merging**
