### PR TITLE
Box Developer Edition, part one

### PR DESCRIPTION
**Pull request by bgoldman**
Implementing https://github.com/box/box-windows-sdk-v2/issues/106

This is incomplete. I'm having serious issues getting the packages installed for the .NET version target (4.0) and needed to change it to 4.5. I kind of got it to work, but then a bunch of other things broke that shouldn't have broken.

The test project worked perfectly fine, but the integration is having these problems.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @bgoldman has signed the CLA. Thanks for the pull request!

**Comment by varungu** [comment]
@bgoldman I will try to fix it today. Can you explain what all this change do and what is pending?

**Comment by varungu** [comment]
@bgoldman The problem is that you are using "BouncyCastle", which is not compatible with portable-net4. You should instead use "Portable.BouncyCastle". Please try it out and let me know if it fixes your issues.

We cannot change the target to .net4.5, this will break this SDK for lot of platforms.

**Comment by cburnette** [comment]
hi @varungu @bgoldman , you are correct that we can't change the target platform for this SDK.  The changes by @bgoldman are to support Box Platform Edition, but I have a separate branch going to roll these changes (and a few others) in and keep the targets the same.

**Comment by bgoldman** [comment]
@varungu I have already tried Portable.BouncyCastle prior to submitting, but had issues with the other packages. I changed it back to the regular BouncyCastle after I changed the .NET version target.

@cburnette If you're able to keep the targets the same but still these packages in there and the code working, that would be great :)

**Comment by cburnette** [comment]
Box Platform support has been added via a different branch.

**Pull request closed without merging**
