### PR TITLE
Create shared link

### PR DESCRIPTION
**Pull request by marek-vysoky**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @marek-vysoky has signed the CLA. Thanks for the pull request!

**Comment by coolboy** [comment]
@marek-vysoky conflict

**Comment by marek-vysoky** [comment]
Can you try again? I check it, and I don't have conflict.

**Comment by coolboy** [comment]
@marek-vysoky conflict

**Comment by marek-vysoky** [comment]
Conflict resolved

**Comment by cburnette** [comment]
@coolboy Let's review this one.

**Comment by cburnette** [comment]
functionality already rolled into master

**Pull request closed without merging**
