### PR TITLE
Changed BoxRequestExtensions Param<T> to take an IEnumerable<string> collection rather than a List<string>

### PR DESCRIPTION
**Pull request by Dave-Lowndes**
…so that all callers can benefit from being able to pass any collection type (such as read only or arrays) - since that's often all that is needed by the calling application.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @Dave-Lowndes, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by Dave-Lowndes** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @Dave-Lowndes has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by coolboy** [comment]
Thank you @Dave-Lowndes 
I am traveling to China right now, please expect some delay of merging this PR.

**Comment by Dave-Lowndes** [comment]
Cheers, I hope the changes are beneficial.

**Comment by coolboy** [comment]
Yes thank you for your contribution

**Pull request merged**
