### PR TITLE
Add optional fields parameter for GetUserInformationAsync call

### PR DESCRIPTION
**Pull request by Cpcrook**
…for consistency with underlying REST API

Pretty straight forward and should handle issue #601

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @Cpcrook has signed the CLA. Thanks for the pull request!

**Comment by carycheng** [comment]
@Cpcrook, thank you for the pr! Since it is a breaking change to change the interface, we would probably have to have an override for GetUserInformationAsync() with the fields. This is something our team can definitely take over and bring to the end.

**Comment by carycheng** [comment]
#605

**Comment by carycheng** [comment]
#605

**Pull request closed without merging**
