### PR TITLE
Update BoxCollaborationUserRequest.cs

### PR DESCRIPTION
**Pull request by kiko-rodriguez**
This update allows to add Collaborations by user-id or group-id

https://box-content.readme.io/reference#add-a-collaboration

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @kiko-rodriguez, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by kiko-rodriguez** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @kiko-rodriguez has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by cburnette** [comment]
BoxRequestEntity (super-class of BoxCollaborationUserRequest) already contains Id and Type properties.  So you can already do this.  Thanks though!

**Pull request closed without merging**
