### PR TITLE
Update collections.md

### PR DESCRIPTION
**Pull request by cbetta**
Add variant code sample tag for collections

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @cbetta has signed the CLA. Thanks for the pull request!

**Comment by PJSimon** [comment]
@cbetta I don't know how to kick off a new AppVeyor build...

**Comment by PJSimon** [comment]
@cbetta I guess you can merge this (after updating the branch), even if the check fails, since the change is just a comment.

**Comment by PJSimon** [comment]
Sorry, closed by accident, then re-opened.

**Comment by cbetta** [comment]
@PJSimon Updated branch. I can't merge (not authorized to).

**Pull request merged**
