### PR TITLE
#389 virtual model properties for mocking accessibility

### PR DESCRIPTION
**Pull request by Cpcrook**
Per issue #389  and PR #602 this is the second half of my fix for the referenced issue.

It makes all non-EventSource model class properties virtual so they can be mocked with a mocking framework such as Moq without issue.  Combined with #602 this should allow effective mocking of a decent amount of this SDK.

In order to minimize impact to the code base, I decided against implementing interfaces for all of these model classes, as I don't believe there is any significant payoff to doing so as compared to virtual props.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @Cpcrook has signed the CLA. Thanks for the pull request!

**Comment by carycheng** [comment]
@Cpcrook, thank you for this pr! We really appreciate it, we will take a look at this and keep you updated

**Comment by PJSimon** [comment]
Hi @Cpcrook!
Thanks so much for this contribution!  I just wanted to follow up and give you an expectation of time frame for our response.  

The team is focused on a release this week for the [box-ios-sdk](https://github.com/box/box-ios-sdk).  So, we will review your PR on Thursday of next week and will respond later that day!

Thanks again!

**Comment by mwwoda** [comment]
Hi @Cpcrook!
Thank you once again for the contribution! I know that a lot time passed since the last update from us but we're working to integrate your changes into the main branch ASAP! I made some changes to your PR to keep it up-to-date with newest codebase, hope you don't mind. We plan to ship it with the next major release of the SDK!

@mwwoda

**Review by sujaygarlanka — DISMISSED** [review]

**Comment by mwwoda** [comment]
I moved all the changes to separate PR because of appveyor issues when building from fork #735.

**Pull request closed without merging**
