### PR TITLE
Multiput upload enhancement

### PR DESCRIPTION
**Pull request by coolboy**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @coolboy has signed the CLA. Thanks for the pull request!

**Comment by cburnette** [comment]
@coolboy I assume this is still loading all the file into memory?

**Comment by coolboy** [comment]
@cburnette this will load files into memory, but not all.

Internally it will load 5*8MB at the same time max and will release once the uploadpart is done

Per my testing (from 10MB -> 3GB files), the peak memory usage is around 250MB and avg. is around 100MB

**Comment by coolboy** [comment]
@cburnette of course if you have the code sample showing me how to handle it better, I will see if I can update it.

**Pull request merged**
