### PR TITLE
Lock and Unlock

### PR DESCRIPTION
**Pull request by marek-vysoky**
Adding comments, extending request object, verifying implementation
UpdateFileLock_ValidResponse_ValidFile

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @marek-vysoky has signed the CLA. Thanks for the pull request!

**Comment by marek-vysoky** [comment]
Renaming FieldLockType  to FieldType, LockType to Type

**Comment by coolboy** [comment]
@marek-vysoky conflict

**Comment by marek-vysoky** [comment]
@coolboy Conflict resolved

**Comment by cburnette** [comment]
@coolboy his changes were based on incorrect documentation.  I've changed it back and added a LockAsync convenience method

**Pull request merged**
