### PR TITLE
Throw exception on private key read error

### PR DESCRIPTION
**Pull request by coolboy**
#311

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @coolboy has signed the CLA. Thanks for the pull request!

**Comment by coolboy** [comment]
Want to look at it? @Dave-Lowndes

**Comment by Dave-Lowndes** [comment]
That change is what I'd envisaged. I'm not too sure about the exception text message though - mostly because I don't know anything about PemReader or this code.

When I debugged the code, the PemReader constructor worked, but the result of ReadObject was null.
Rather than "Private key read error!", might it be more useful to say "Invalid private key" (though I don't know if the key I have is invalid or not)?

**Comment by coolboy** [comment]
@Dave-Lowndes updated the message and merged

Thanks for the feedback!

**Comment by Dave-Lowndes** [comment]
Thank you for such a speedy response.

**Pull request merged**
