### PR TITLE
Copy file

### PR DESCRIPTION
**Pull request by marek-vysoky**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @marek-vysoky has signed the CLA. Thanks for the pull request!

**Comment by coolboy** [comment]
@marek-vysoky conflict

**Comment by marek-vysoky** [comment]
I check this and I don't have conflict for master branch. Can you try again?

**Comment by coolboy** [comment]
Hi @marek-vysoky I am still getting 

This branch has conflicts that must be resolved
 Use the command line to resolve conflicts before continuing.
Conflicting files
Box.V2.Test/BoxResourceManagerTest.cs

**Comment by marek-vysoky** [comment]
I've merged master to this branch, resolved the conflict and pushed the changes

**Comment by coolboy** [comment]
@marek-vysoky please resolve the conflict

**Comment by marek-vysoky** [comment]
I've resolved conflict.

**Pull request merged**
