### PR TITLE
Update files.md

### PR DESCRIPTION
**Pull request by cbetta**
Add better tags for download samples

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @cbetta has signed the CLA. Thanks for the pull request!

**Comment by PJSimon** [comment]
@cbetta Sorry, I don't know how to retry the AppVeyor build.

**Comment by PJSimon** [comment]
@cbetta I guess you can merge this (after updating the branch), even if the check fails, since the change is just a comment.

**Comment by cbetta** [comment]
@PJSimon Updated branch. I can't merge (not authorized to).

**Pull request merged**
