### PR TITLE
Download file

### PR DESCRIPTION
**Pull request by marek-vysoky**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @marek-vysoky has signed the CLA. Thanks for the pull request!

**Comment by coolboy** [comment]
@marek-vysoky conflict

**Comment by marek-vysoky** [comment]
I've merged master to this branch, resolved the conflict and pushed the changes

**Comment by coolboy** [comment]
@marek-vysoky conflict

**Comment by marek-vysoky** [comment]
Conflict resolved

**Comment by cburnette** [comment]
@coolboy Let's review this one.  The GetDownloadUriAsync method is not the right place for this range stuff.

**Comment by cburnette** [comment]
GetDownloadUriAsync method is not the right place for range functionality

**Pull request closed without merging**
