### PR TITLE
Switch over to DateTimeOffset

### PR DESCRIPTION
**Pull request by BryceBarbara**
This is to address a long time shortcoming of the SDK which is the improper handling of dates and times.

This should address #394

### CODE REVIEW

**Comment by BryceBarbara** [comment]
It looks like the integration tests are failing but that appears to be a problem that existed prior to this PR. Let me know if there's something I need to do to.

**Comment by PJSimon** [comment]
Thanks for the contribution, @BryceBarbara !  We'll take a look ASAP!

**Comment by BryceBarbara** [comment]
Any update on the status of this?

**Comment by mwwoda** [comment]
Hi @BryceBarbara 
This PR was closed by mistake. Sorry for that! The work will be continued under #749.

Thanks,
@mwwoda

**Pull request closed without merging**
