### PR TITLE
Added tags (Fixes #87)

### LINKED ISSUE #87: Tag field is not exposed in SDK
The Box API provides a "tags" field but this is not exposed in the SDK.

### PR DESCRIPTION
**Pull request by samiringo**
- Exposed tags field in BoxItem for reading (FieldTags)
- Added tags field to BoxItemRequest to be able to update the field
- Updated file unit tests

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @samiringo, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by samiringo** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @samiringo has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by samiringo** [comment]
Is there any news on this change? Just wondering when this will be looked at.

Thanks!

**Comment by brianytang** [comment]
Merged! Thanks for the pull request

**Pull request merged**
