### PR TITLE
Add WebProxy Support in BoxConfig

### PR DESCRIPTION
**Pull request by atulmish**
Summary of the feature:
Similar to the issue https://github.com/box/box-windows-sdk-v2/issues/538 our app requires to use an HTTP proxy. 

In this commit:
 - Update IBoxConfiguration to have IWebProxy property
 - Update HttpRequestHandler to use Http proxy if it is configured.
 - Add WebProxy Sample Project to demonstrate how to use it.

Please let me know if anything else is required to be able to get this feature merged. We urgently need this feature.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @atulmish, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by atulmish** [comment]
CLA signed

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @atulmish. Can you please try again?

**Comment by atulmish** [comment]
CLA signed

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @atulmish. Can you please try again?

**Comment by atulmish** [comment]
CLA signed

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @atulmish. Can you please try again?

**Comment by atulmish** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @atulmish has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by mattwiller** [comment]
@atulmish Thank for the PR!  Our team will need to do some testing to ensure the PR works the way we'd like it to — we'll tentatively aim to get this into a release next week

**Comment by atulmish** [comment]
Hi @mattwiller, Please let me know if anything else is required from my end to get this merged.

**Comment by mattwiller** [comment]
@atulmish We just released v3.18.0 of the SDK, which includes your change.  Thanks again for the PR — let us know if there's anything else we can help with!

**Pull request merged**
